### ISSUE TITLE
Is there a way you could link to bankai?

### ISSUE THREAD

**Issue by mattkatz** [willdayble/willdayble.com#1]
I finally lost the drive I had those amazing perfect songs on and I'd love someway to get them again other than searching youtube. 

Bankai is amazing and makes this world better 🤘

**Comment by willdayble** [comment]
Oh woah, er... I think most of it is on Soundcloud? I must admit I haven't checked lately. I'm real bad at backups, haha!

**Comment by mattkatz** [comment]
It's on soundcloud! Thanks so much!
